services:
  - type: web
    name: my-nextjs-app
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      # Clerk
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        sync: false
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL
        sync: false
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL
        sync: false

      # Supabase
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false

      # Next Webhook Secret
      - key: NEXT_WEBHOOK_SECRET
        sync: false

      # Redis
      - key: REDIS_URL
        sync: false

      # GCP Storage
      - key: GCP_PROJECT_ID
        sync: false
      - key: GCP_CLIENT_EMAIL
        sync: false
      - key: GCP_PRIVATE_KEY
        sync: false
      - key: GCS_BUCKET
        sync: false

      # Cloudinary
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false